apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deploy-3
  labels:
    app: nginx-docker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-docker
  template:
    metadata:
      labels:
        app: nginx-docker
    spec:
      containers:
      - name: nginx-docker
        image: sharvesh923/my-nginx:1.4
        ports:
        - containerPort: 80
      imagePullSecrets:
        - name: docker-hub-private
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: nginx-docker
  name: my-service
spec:
  selector:
    app: nginx-docker
  type: NodePort
  ports:
  - nodePort: 31200
    protocol: TCP
    port: 80
    targetPort: 80

