apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deploy-2
  labels:
    app: nginx-ecr
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx-ecr
  template:
    metadata:
      labels:
        app: nginx-ecr
    spec:
      containers:
      - name: nginx-ecr
        image: 039608100464.dkr.ecr.us-east-2.amazonaws.com/k8s:latest
        ports:
        - containerPort: 80
      imagePullSecrets:
          - name: my-secret

apiVersion: v1
kind: Service
metadata:
  labels:
    app: nginx-ecr
  name: my-service
spec:
  selector:
    app: nginx
  type: NodePort
  ports:
  - nodePort: 31115
    protocol: TCP
    port: 80
    targetPort: 80
